services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tsdproxy-data:/data
    environment:
      - TSDPROXY_AUTHKEY=tskey-auth-kNS2iWq6tk11CNTRL-LjNcKS5mmZaT2qHg2jLVZaY2MiUPd24h

  memos:
    image: neosmemo/memos:stable
    restart: unless-stopped
    expose:
      - 5230
    volumes:
      - ./memos-data:/var/opt/memos
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=memos
      - tsdproxy.port=5230
      - tsdproxy.funnel=true

  ollama-brgy-api:
    build:
      context: ../../development/ws-monica
    restart: unless-stopped
    expose:
      - 6000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=ollama-brgy-api
      - tsdproxy.port=6000
      - tsdproxy.funnel=true

  star-api:
    build:
      context: ../star
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=star-api
      - tsdproxy.port=3000
      - tsdproxy.funnel=true

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./uploads:/app/uploads:ro
      - ./caddy-data:/data
      - ./caddy-config:/config
    environment:
      - BASE_URL=":80"
    labels:
      - tsdproxy.enable=true
      - tsdproxy.name=main
      - tsdproxy.port=80
      - tsdproxy.funnel=true

  chibisafe:
    image: chibisafe/chibisafe:latest
    restart: unless-stopped
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    depends_on:
      - chibisafe_server

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - ./database:/app/database
      - ./uploads:/app/uploads
      - ./logs:/app/logs
